
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class tabla_simbolos {
  /* terminals */
  public static final int r_contenido = 11;
  public static final int r_nombre = 8;
  public static final int r_documento = 9;
  public static final int r_formato = 10;
  public static final int abrir = 2;
  public static final int EOF = 0;
  public static final int nombre_archivo = 13;
  public static final int r_directorio = 6;
  public static final int directorio = 12;
  public static final int error = 1;
  public static final int contenido = 14;
  public static final int fin = 4;
  public static final int cerrar = 3;
  public static final int r_carpeta = 7;
  public static final int r_estructura = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "abrir",
  "cerrar",
  "fin",
  "r_estructura",
  "r_directorio",
  "r_carpeta",
  "r_nombre",
  "r_documento",
  "r_formato",
  "r_contenido",
  "directorio",
  "nombre_archivo",
  "contenido"
  };
    static int comillas;
}

